[package]
name = "grid_guru_avail"
version = "0.1.0"
edition = "2021"

[dependencies]
avail-rust = { git = "https://github.com/availproject/avail-rust", tag = "v0.1.4" }
tokio = { version = "1.38.0", features = ["full"] }
dotenvy = "0.15.7"


